version: "3.9"

services:
  crm-chatbot-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-chatbot-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped